### ISSUE TITLE
Is Preprocessor.cpp a reimplementation of B+E or what extra elements does it have?

### ISSUE THREAD

**Issue by msoos** [meelgroup/KCBox#1]
Hi,

I have to admit, https://github.com/meelgroup/KCBox/blob/main/src/Preprocessor.cpp is super impressive. I'd like to know if it has elements that are not present in B+E related to equivalent literal replacement? It seems to have a similar set of techniques as B+E: gate-based variable removal, backbone computation, toplevel equivalent literal replacement etc. However, you mention about special (perhaps non-toplevel) equivalent literal replacement in particular in the README, so I'm curious. I thought the non-toplevel eqLit replacement is only done during the knowledge compilation phase?

Thanks,

Mate

**Comment by ydotlai** [comment]
> Hi,
> 
> I have to admit, https://github.com/meelgroup/KCBox/blob/main/src/Preprocessor.cpp is super impressive. I'd like to know if it has elements that are not present in B+E related to equivalent literal replacement? It seems to have a similar set of techniques as B+E: gate-based variable removal, backbone computation, toplevel equivalent literal replacement etc. However, you mention about special (perhaps non-toplevel) equivalent literal replacement in particular in the README, so I'm curious. I thought the non-toplevel eqLit replacement is only done during the knowledge compilation phase?
> 
> Thanks,
> 
> Mate
Hi Mate,

PreLite reimplemented most of technologies used in pmc. I think some technologies are also used in B+E. Roughly speaking, there are no extra technologies.

Non-toplevel eqLit replacement is done in the https://github.com/meelgroup/KCBox/blob/main/src/Extensive_Inprocessor.cpp.

**Comment by msoos** [comment]
Thanks for the quick response! What is PMC? Can you give a link to the code and the paper if they exist?

Thanks,

Mate

**Comment by ydotlai** [comment]
This is the link to pmc: http://www.cril.univ-artois.fr/KC/pmc.html
