### ISSUE TITLE
ExactMC/PartialKC fail on an example CNF file with "Assertion `new_max_var < _max_var'"

### ISSUE THREAD

**Issue by chivdan** [meelgroup/KCBox#2]
On the attached example ExactMC and PartialKC (commit 5ee00f631743a3b6fbe5aa6a27b591b3efe8b8f6) fail with the following assertion: 

> Instance name: error.cnf
> Thu 23 Mar 2023 01:14:44 PM UTC
> Counting models...
> Begin preprocess...
> Number of original variables: 113
> Number of original clauses: 113
> s SATISFIABLE
> Number of unsimplifiable variables: **4294967183** (113 unit, 0 equ, 113 omit)
> Number of unsimplifiable non-unary clauses: 0
> Preprocessing Time: 0.000446
>     Time of SAT: 0.000423
>     Time of blocking clauses: 1e-06
>     Time of blocking literals: 1e-06
>     Time of replacing literal equivalency: 6e-06
> KCBox: /home/simcenter/misc/KCBox/src/Primitive_Types/Assignment.h:380: void KCBox::Model_Pool::Shrink_Max_Var(KCBox::Variable, KCBox::Variable*): Assertion `new_max_var < _max_var' failed.
> Aborted

Run as follows: `KCBox ExactMC error.cnf`
The highlighted "Number of unsimplifiable variables" values also seems a bit strange to me, given that the CNF file only has 113 variables.

I'd be glad to help fix the issue and send a pull request, if one of the developers has an idea where to look.

[error.tar.gz](https://github.com/meelgroup/KCBox/files/11051198/error.tar.gz)

**Comment by ydotlai** [comment]
Thank you for reporting this issue. I  will fix it in the coming days.

**Comment by ydotlai** [comment]
I think I have fixed the bug. Would it be possible for you to have a try again?

**Comment by chivdan** [comment]
It works now, thanks a lot!
