### ISSUE TITLE
Compilers/DNNF_Compiler.h missing

### ISSUE THREAD

**Issue by mahi045** [meelgroup/KCBox#5]
Hi,
I cannot build KCBox because DNNF_Compiler is missing from src/Compilers.
```
/KCBox/src/Main.cpp:6:10: fatal error: Compilers/DNNF_Compiler.h: No such file or directory
 #include "Compilers/DNNF_Compiler.h"
```

Also, "src/KC_Languages/DecDNNF.cpp" is missing, which is required by CMakeLists.txt.

Thanks.

-Mahi

**Comment by ydotlai** [comment]
added. If you have any issues, please let me know.
