### ISSUE TITLE
The usage of ExactMC

### ISSUE THREAD

**Issue by ylyzty** [meelgroup/KCBox#6]
Both the kdepth and the format parameters are IntOption type.
![Options](https://github.com/meelgroup/KCBox/assets/50573767/55efb983-0297-40cc-94e0-eac2ec79a947)

When I execute commands like this "./ExactMC --kdepth 64 ./simple_v3_c2.cnf", I can succeed.
But executing this command "./ExactMC --format 1 ./simple_v3_c2.cnf" is not possible!
![format](https://github.com/meelgroup/KCBox/assets/50573767/a26b792b-2dd7-40f3-b2a4-cf08c62e36a8)

Could you tell me why?

**Comment by ydotlai** [comment]
--format is for weighted model counting
