### ISSUE TITLE
smooth OBDD[and] wmc

### ISSUE THREAD

**Issue by zeroed1** [meelgroup/KCBox#7]
When I applied the smoothed OBDD[and] to the WMC of problog2, I got different results. The first picture is the result of the non-smoothed OBDD[and] weighted model count, and the third picture is the ddnnf weighted model. Counting results, the second picture is the counting results of the non-smoothed OBDD[and] weighted model. You can see that the smoothobdd[and] result in smoker(5) is incorrect but the obdd[and] result is correct. Then you can see that the smoothed OBDD[and] root node and the non-smoothed OBDD[and] result are different .cnf file is at the bottom
[problog2cnf.txt](https://github.com/user-attachments/files/17476049/problog2cnf.txt)
![default](https://github.com/user-attachments/assets/cafb534b-016d-48bb-b7a8-16d1e9028f2a)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=997677333386873195 skey=@crypt_12604a37_8ece81a8e8010ce1a46badc2395620f3 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/072e26d1-1be5-45e3-8f2a-a695c4278e82)
![image](https://github.com/user-attachments/assets/c74719dc-9eb6-4f5b-89cc-81ef1d586a6b)

**Comment by ydotlai** [comment]
Fixed a bug. Please check if it dealt with your issue.
